# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'casing3D.ui'
#
# Created: Wed Feb 25 15:55:47 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_casing3D(object):
    def setupUi(self, casing3D):
        casing3D.setObjectName("casing3D")
        casing3D.setEnabled(True)
        casing3D.resize(1059, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/nemo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        casing3D.setWindowIcon(icon)
        casing3D.setStyleSheet("")
        self.hGL = QtWidgets.QHBoxLayout(casing3D)
        self.hGL.setSpacing(0)
        self.hGL.setContentsMargins(0, 0, 0, 0)
        self.hGL.setObjectName("hGL")
        self.option = QtWidgets.QWidget(casing3D)
        self.option.setMaximumSize(QtCore.QSize(180, 16777215))
        self.option.setObjectName("option")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.option)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 6, 2, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbViewport = QtWidgets.QGroupBox(self.option)
        self.gbViewport.setFlat(True)
        self.gbViewport.setObjectName("gbViewport")
        self.verticalLayout.addWidget(self.gbViewport)
        self.hViewport = QtWidgets.QHBoxLayout()
        self.hViewport.setObjectName("hViewport")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hViewport.addItem(spacerItem)
        self.viewtop = QtWidgets.QRadioButton(self.option)
        self.viewtop.setObjectName("viewtop")
        self.hViewport.addWidget(self.viewtop)
        self.viewfront = QtWidgets.QRadioButton(self.option)
        self.viewfront.setChecked(True)
        self.viewfront.setObjectName("viewfront")
        self.hViewport.addWidget(self.viewfront)
        self.verticalLayout.addLayout(self.hViewport)
        self.gbShow = QtWidgets.QGroupBox(self.option)
        self.gbShow.setFlat(True)
        self.gbShow.setObjectName("gbShow")
        self.verticalLayout.addWidget(self.gbShow)
        self.hShowTool = QtWidgets.QHBoxLayout()
        self.hShowTool.setObjectName("hShowTool")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hShowTool.addItem(spacerItem1)
        self.showMFC = QtWidgets.QCheckBox(self.option)
        self.showMFC.setChecked(True)
        self.showMFC.setObjectName("showMFC")
        self.hShowTool.addWidget(self.showMFC)
        self.showMTD = QtWidgets.QCheckBox(self.option)
        self.showMTD.setChecked(True)
        self.showMTD.setObjectName("showMTD")
        self.hShowTool.addWidget(self.showMTD)
        self.hShowTool.setStretch(0, 2)
        self.hShowTool.setStretch(1, 4)
        self.hShowTool.setStretch(2, 4)
        self.verticalLayout.addLayout(self.hShowTool)
        self.hShowData = QtWidgets.QHBoxLayout()
        self.hShowData.setObjectName("hShowData")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hShowData.addItem(spacerItem2)
        self.showData = QtWidgets.QCheckBox(self.option)
        self.showData.setChecked(False)
        self.showData.setObjectName("showData")
        self.hShowData.addWidget(self.showData)
        self.showDep = QtWidgets.QCheckBox(self.option)
        self.showDep.setObjectName("showDep")
        self.hShowData.addWidget(self.showDep)
        self.hShowData.setStretch(0, 2)
        self.hShowData.setStretch(1, 4)
        self.hShowData.setStretch(2, 4)
        self.verticalLayout.addLayout(self.hShowData)
        self.hShowGrid = QtWidgets.QHBoxLayout()
        self.hShowGrid.setObjectName("hShowGrid")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hShowGrid.addItem(spacerItem3)
        self.showClip = QtWidgets.QCheckBox(self.option)
        self.showClip.setChecked(False)
        self.showClip.setObjectName("showClip")
        self.hShowGrid.addWidget(self.showClip)
        self.showApart = QtWidgets.QCheckBox(self.option)
        self.showApart.setChecked(False)
        self.showApart.setObjectName("showApart")
        self.hShowGrid.addWidget(self.showApart)
        self.hShowGrid.setStretch(0, 2)
        self.hShowGrid.setStretch(1, 4)
        self.hShowGrid.setStretch(2, 4)
        self.verticalLayout.addLayout(self.hShowGrid)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.showBack = QtWidgets.QCheckBox(self.option)
        self.showBack.setChecked(True)
        self.showBack.setObjectName("showBack")
        self.horizontalLayout.addWidget(self.showBack)
        self.horizontalLayout.setStretch(0, 19)
        self.horizontalLayout.setStretch(1, 81)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gbDepth = QtWidgets.QGroupBox(self.option)
        self.gbDepth.setFlat(True)
        self.gbDepth.setObjectName("gbDepth")
        self.verticalLayout.addWidget(self.gbDepth)
        self.hDepthLength = QtWidgets.QHBoxLayout()
        self.hDepthLength.setSpacing(6)
        self.hDepthLength.setContentsMargins(-1, -1, 6, -1)
        self.hDepthLength.setObjectName("hDepthLength")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hDepthLength.addItem(spacerItem5)
        self.lbllenth = QtWidgets.QLabel(self.option)
        self.lbllenth.setObjectName("lbllenth")
        self.hDepthLength.addWidget(self.lbllenth)
        self.dispLength = QtWidgets.QDoubleSpinBox(self.option)
        self.dispLength.setMinimumSize(QtCore.QSize(0, 0))
        self.dispLength.setDecimals(0)
        self.dispLength.setMinimum(1.0)
        self.dispLength.setMaximum(500.0)
        self.dispLength.setProperty("value", 20.0)
        self.dispLength.setObjectName("dispLength")
        self.hDepthLength.addWidget(self.dispLength)
        self.hDepthLength.setStretch(0, 2)
        self.hDepthLength.setStretch(1, 1)
        self.hDepthLength.setStretch(2, 7)
        self.verticalLayout.addLayout(self.hDepthLength)
        self.hlDepthGoto = QtWidgets.QHBoxLayout()
        self.hlDepthGoto.setSpacing(6)
        self.hlDepthGoto.setContentsMargins(-1, -1, 6, -1)
        self.hlDepthGoto.setObjectName("hlDepthGoto")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlDepthGoto.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.option)
        self.label.setObjectName("label")
        self.hlDepthGoto.addWidget(self.label)
        self.depth = QtWidgets.QDoubleSpinBox(self.option)
        self.depth.setMinimumSize(QtCore.QSize(0, 0))
        self.depth.setDecimals(0)
        self.depth.setObjectName("depth")
        self.hlDepthGoto.addWidget(self.depth)
        self.hlDepthGoto.setStretch(0, 2)
        self.hlDepthGoto.setStretch(1, 1)
        self.hlDepthGoto.setStretch(2, 7)
        self.verticalLayout.addLayout(self.hlDepthGoto)
        self.hDepth = QtWidgets.QHBoxLayout()
        self.hDepth.setContentsMargins(-1, 0, 10, -1)
        self.hDepth.setObjectName("hDepth")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hDepth.addItem(spacerItem7)
        self.depSelect = QtWidgets.QSlider(self.option)
        self.depSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.depSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.depSelect.setMaximum(100)
        self.depSelect.setSingleStep(1)
        self.depSelect.setPageStep(5)
        self.depSelect.setOrientation(QtCore.Qt.Horizontal)
        self.depSelect.setObjectName("depSelect")
        self.hDepth.addWidget(self.depSelect)
        self.verticalLayout.addLayout(self.hDepth)
        self.hDepthAuto = QtWidgets.QHBoxLayout()
        self.hDepthAuto.setObjectName("hDepthAuto")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hDepthAuto.addItem(spacerItem8)
        self.depAuto = QtWidgets.QCheckBox(self.option)
        self.depAuto.setMinimumSize(QtCore.QSize(0, 0))
        self.depAuto.setObjectName("depAuto")
        self.hDepthAuto.addWidget(self.depAuto)
        self.hDepthAuto.setStretch(0, 35)
        self.hDepthAuto.setStretch(1, 65)
        self.verticalLayout.addLayout(self.hDepthAuto)
        self.gbColor = QtWidgets.QGroupBox(self.option)
        self.gbColor.setFlat(True)
        self.gbColor.setObjectName("gbColor")
        self.verticalLayout.addWidget(self.gbColor)
        self.hColortitle = QtWidgets.QHBoxLayout()
        self.hColortitle.setObjectName("hColortitle")
        self.lblColorMFC = QtWidgets.QLabel(self.option)
        self.lblColorMFC.setContentsMargins(2, 2, 2, 2)
        self.lblColorMFC.setObjectName("lblColorMFC")
        self.hColortitle.addWidget(self.lblColorMFC)
        self.lblColorMTD = QtWidgets.QLabel(self.option)
        self.lblColorMTD.setContentsMargins(2, 2, 2, 2)
        self.lblColorMTD.setObjectName("lblColorMTD")
        self.hColortitle.addWidget(self.lblColorMTD)
        self.verticalLayout.addLayout(self.hColortitle)
        self.hColor = QtWidgets.QHBoxLayout()
        self.hColor.setObjectName("hColor")
        self.mfcColor = QtWidgets.QTableWidget(self.option)
        self.mfcColor.setMaximumSize(QtCore.QSize(16777215, 400))
        self.mfcColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mfcColor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mfcColor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mfcColor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mfcColor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mfcColor.setWordWrap(False)
        self.mfcColor.setCornerButtonEnabled(False)
        self.mfcColor.setObjectName("mfcColor")
        self.mfcColor.setColumnCount(2)
        self.mfcColor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.mfcColor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mfcColor.setHorizontalHeaderItem(1, item)
        self.mfcColor.horizontalHeader().setVisible(False)
        self.mfcColor.horizontalHeader().setDefaultSectionSize(40)
        self.mfcColor.horizontalHeader().setHighlightSections(True)
        self.mfcColor.horizontalHeader().setMinimumSectionSize(10)
        self.mfcColor.verticalHeader().setVisible(False)
        self.mfcColor.verticalHeader().setDefaultSectionSize(16)
        self.mfcColor.verticalHeader().setMinimumSectionSize(10)
        self.mfcColor.verticalHeader().setSortIndicatorShown(False)
        self.mfcColor.verticalHeader().setStretchLastSection(False)
        self.hColor.addWidget(self.mfcColor)
        self.mtdColor = QtWidgets.QTableWidget(self.option)
        self.mtdColor.setMaximumSize(QtCore.QSize(16777215, 400))
        self.mtdColor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mtdColor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mtdColor.setAlternatingRowColors(False)
        self.mtdColor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mtdColor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mtdColor.setWordWrap(False)
        self.mtdColor.setCornerButtonEnabled(False)
        self.mtdColor.setObjectName("mtdColor")
        self.mtdColor.setColumnCount(2)
        self.mtdColor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.mtdColor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.mtdColor.setHorizontalHeaderItem(1, item)
        self.mtdColor.horizontalHeader().setVisible(False)
        self.mtdColor.horizontalHeader().setDefaultSectionSize(40)
        self.mtdColor.horizontalHeader().setHighlightSections(False)
        self.mtdColor.verticalHeader().setVisible(False)
        self.mtdColor.verticalHeader().setDefaultSectionSize(16)
        self.hColor.addWidget(self.mtdColor)
        self.verticalLayout.addLayout(self.hColor)
        self.hColorButton = QtWidgets.QHBoxLayout()
        self.hColorButton.setObjectName("hColorButton")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hColorButton.addItem(spacerItem9)
        self.colorOK = QtWidgets.QPushButton(self.option)
        self.colorOK.setStyleSheet("")
        self.colorOK.setObjectName("colorOK")
        self.hColorButton.addWidget(self.colorOK)
        self.colorReset = QtWidgets.QPushButton(self.option)
        self.colorReset.setStyleSheet("")
        self.colorReset.setObjectName("colorReset")
        self.hColorButton.addWidget(self.colorReset)
        self.verticalLayout.addLayout(self.hColorButton)
        self.gbFile = QtWidgets.QGroupBox(self.option)
        self.gbFile.setFlat(True)
        self.gbFile.setObjectName("gbFile")
        self.verticalLayout.addWidget(self.gbFile)
        self.files = QtWidgets.QListWidget(self.option)
        self.files.setMaximumSize(QtCore.QSize(16777215, 120))
        self.files.setObjectName("files")
        self.verticalLayout.addWidget(self.files)
        self.hFile = QtWidgets.QHBoxLayout()
        self.hFile.setObjectName("hFile")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hFile.addItem(spacerItem10)
        self.importLAS = QtWidgets.QPushButton(self.option)
        self.importLAS.setObjectName("importLAS")
        self.hFile.addWidget(self.importLAS)
        self.saveBmp = QtWidgets.QPushButton(self.option)
        self.saveBmp.setStyleSheet("")
        self.saveBmp.setObjectName("saveBmp")
        self.hFile.addWidget(self.saveBmp)
        self.verticalLayout.addLayout(self.hFile)
        self.hGL.addWidget(self.option)

        self.retranslateUi(casing3D)
        self.mfcColor.cellClicked['int','int'].connect(casing3D.on_color_click)
        self.mtdColor.cellClicked['int','int'].connect(casing3D.on_color_click)
        self.depAuto.clicked['bool'].connect(casing3D.on_auto_depth)
        self.colorOK.clicked.connect(casing3D.on_colorOk_click)
        self.colorReset.clicked.connect(casing3D.on_colorReset_click)
        self.saveBmp.clicked.connect(casing3D.on_savebmp_click)
        self.viewtop.clicked['bool'].connect(casing3D.on_viewport_click)
        self.viewfront.clicked['bool'].connect(casing3D.on_viewport_click)
        self.files.currentTextChanged['QString'].connect(casing3D.on_files_change)
        self.showMFC.clicked['bool'].connect(casing3D.on_show_click)
        self.showMTD.clicked['bool'].connect(casing3D.on_show_click)
        self.showBack.clicked['bool'].connect(casing3D.on_show_click)
        self.showData.clicked['bool'].connect(casing3D.on_show_click)
        self.showClip.clicked['bool'].connect(casing3D.on_show_click)
        self.showApart.clicked['bool'].connect(casing3D.on_show_click)
        self.depth.valueChanged['double'].connect(casing3D.on_set_depth)
        self.dispLength.valueChanged['double'].connect(casing3D.on_depth_len_change)
        self.depSelect.actionTriggered['int'].connect(casing3D.on_change_depth)
        self.importLAS.clicked.connect(casing3D.on_import_las)
        self.showDep.clicked['bool'].connect(casing3D.on_show_click)
        QtCore.QMetaObject.connectSlotsByName(casing3D)

    def retranslateUi(self, casing3D):
        _translate = QtCore.QCoreApplication.translate
        casing3D.setWindowTitle(_translate("casing3D", "套管成像 (鼠标控制：左键旋转 右键缩放 中键拉伸 滚轮深度)"))
        self.gbViewport.setTitle(_translate("casing3D", "样式"))
        self.viewtop.setText(_translate("casing3D", "顶视图  "))
        self.viewfront.setText(_translate("casing3D", "前视图  "))
        self.gbShow.setTitle(_translate("casing3D", "显示"))
        self.showMFC.setText(_translate("casing3D", "MFC井径"))
        self.showMTD.setText(_translate("casing3D", "MTD测厚"))
        self.showData.setText(_translate("casing3D", "数据"))
        self.showDep.setText(_translate("casing3D", "深度"))
        self.showClip.setText(_translate("casing3D", "半管"))
        self.showApart.setText(_translate("casing3D", "分离"))
        self.showBack.setText(_translate("casing3D", "黑背景"))
        self.gbDepth.setTitle(_translate("casing3D", "深度"))
        self.lbllenth.setToolTip(_translate("casing3D", "单位：米/荧屏"))
        self.lbllenth.setText(_translate("casing3D", "长度"))
        self.label.setText(_translate("casing3D", "深度"))
        self.depAuto.setText(_translate("casing3D", "自动滚屏"))
        self.gbColor.setTitle(_translate("casing3D", "颜色"))
        self.lblColorMFC.setText(_translate("casing3D", "MFC内径%"))
        self.lblColorMTD.setText(_translate("casing3D", "MTD厚度%"))
        self.mfcColor.setToolTip(_translate("casing3D", "(实测半径-原始半径) / 厚度"))
        item = self.mfcColor.horizontalHeaderItem(0)
        item.setText(_translate("casing3D", "差值"))
        item = self.mfcColor.horizontalHeaderItem(1)
        item.setText(_translate("casing3D", "颜色"))
        self.mtdColor.setToolTip(_translate("casing3D", "实测厚度 / 原始厚度"))
        item = self.mtdColor.horizontalHeaderItem(0)
        item.setText(_translate("casing3D", "差值"))
        item = self.mtdColor.horizontalHeaderItem(1)
        item.setText(_translate("casing3D", "颜色"))
        self.colorOK.setText(_translate("casing3D", "确定"))
        self.colorReset.setText(_translate("casing3D", "缺省"))
        self.gbFile.setTitle(_translate("casing3D", "文件"))
        self.importLAS.setText(_translate("casing3D", "导入LAS"))
        self.saveBmp.setText(_translate("casing3D", "保存图片"))

import nemo_rc
